### ISSUE TITLE
Reflexion sur l'imc et les graphiques associés

### ISSUE THREAD

**Issue by MarieHuart93** [MarieHuart93/biometry#1]
Salut @GuyliannEngels ,

Je suis en pleine recherche sur l'imc. Je ne trouve pas une information de qualité sur les classes de l'imc. Tu n'aurais pas une piste de rélféxion ?

**Comment by GuyliannEngels** [comment]
Salut @MarieHuart93 ,

Effectivement, on tombe souvent sur des sites web bidon qui propose des calculateurs d'imc. Je pense qu'un site de confiance est le site de l'OMS. As tu regardé de de ce côte là ? 

<https://www.euro.who.int/en/health-topics/disease-prevention/nutrition/a-healthy-lifestyle/body-mass-index-bmi> 

On pourrait utiliser ces classes afin de progresser dans notre analyse graphique
